import { createContext, useContext, useState } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  lang: Language;
  toggleLang: () => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.tours': 'Tours',
    'nav.fleet': 'Fleet',
    'nav.booking': 'Booking',
    'nav.about': 'About',
    'nav.contact': 'Contact',

    // Hero
    'hero.title': 'Explore Panama with Comfort, Safety & Confidence',
    'hero.subtitle': 'Private transportation, airport transfers and unforgettable tours across Panama. Experience the best of the tropics with a first-class executive touch.',
    'hero.btn.contact': 'Contact Us',
    'hero.btn.tours': 'Explore Tours',
    'hero.dock.drivers': 'Professional Drivers',
    'hero.dock.vehicles': 'Comfortable Vehicles',
    'hero.dock.transfers': 'Safe Transfers',
    'hero.dock.prices': 'Affordable Prices',

    // Footer
    'footer.description': 'Leading premium transportation and tourism logistics in the Republic of Panama since 2012.',
    'footer.quicklinks': 'Quick Links',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.faq': 'FAQ',
    'footer.corporate': 'Corporate Travel',
    'footer.services': 'Services',
    'footer.airport': 'Airport Transfers',
    'footer.citytours': 'City Tours',
    'footer.intercity': 'Inter-city Travel',
    'footer.events': 'Special Events',
    'footer.location': 'Location',
    'footer.address': 'Ave. Federico Boyd & Calle 51,\nScotia Plaza Building, 7th Floor,\nBella Vista, Panama City',
    'footer.phone': 'Landline: 310-4785',
    'footer.rights': '© 2026 JM Transport Group Panama. All rights reserved.',
    'about.contact.title': 'Contact & Location',
    'about.contact.address': 'Ave. Federico Boyd & Calle 51,\nScotia Plaza Building, 7th Floor,\nBella Vista, Panama City',
    'about.contact.phone': 'Landline: 310-4785',
    
    // Tours
    'tours.header.subtitle': 'EXCLUSIVE TOURS',
    'tours.header.title': 'Premium Experiences in Panama',
    'tours.header.desc': 'Luxury and corporate itineraries designed to discover Panama\'s most iconic destinations.',

    // San Blas
    'tours.sanblas.title': 'San Blas Islands Getaway',
    'tours.sanblas.desc': 'Summerge yourself in the Caribbean paradise of the San Blas Islands, home to the indigenous Guna people. Turquoise crystal-clear waters, white sand beaches, and a living ancestral culture make this tour a unique and unforgettable experience in the Panamanian Caribbean.',
    'tours.sanblas.meta': 'Full day • San Blas Archipelago',
    'tours.sanblas.hl1': '4×4 Ground Transport',
    'tours.sanblas.hl2': 'Island Boat Navigation',
    'tours.sanblas.hl3': 'Hotel Pickup Included',
    'tours.sanblas.hl4': 'Coral Reef Snorkeling',
    'tours.sanblas.hl5': 'Guna Yala Culture',
    'tours.sanblas.not_inc': 'Not Included: Lunch, beverages, and Guna Yala territory entrance fee.',
    'tours.sanblas.price_label': 'From',
    'tours.sanblas.price': '$125',

    // Monkey Tour
    'tours.monkey.title': 'Monkey Tour',
    'tours.monkey.desc': 'Discover the biodiversity of the Panama Canal and meet its most famous residents up close in their natural habitat. Perfect for photography and wildlife lovers.',
    'tours.monkey.meta': 'Half day trip • Panama Canal Zone',
    'tours.monkey.hl1': 'Canal Boat Cruise',
    'tours.monkey.hl2': 'Wildlife Spotting',
    'tours.monkey.hl3': 'Comfortable Return',
    'tours.monkey.price_label': 'Per person',
    'tours.monkey.price': '$85',

    // Beach Transfers
    'tours.playas.title': 'Transfers to Tourist Destinations',
    'tours.playas.desc': 'Private, comfortable, and punctual executive transportation service door-to-door to major beach areas and premium resorts.',
    'tours.playas.destinations': 'Destinations: Buenaventura, Chiriquí, Boquete, Pedasí, Santa Catalina, Las Mil Polleras, fairs, festivals and any other destination.',
    'tours.playas.meta': 'Oneway / Roundtrip • Available 24/7',
    'tours.playas.hl1': 'Modern Executive Fleet',
    'tours.playas.hl2': 'Unlimited Luggage',
    'tours.playas.hl3': 'Personalized Service',
    'tours.playas.price_label': 'Up to 4 passengers',
    'tours.playas.price': '$125',

    // Historic Colon
    'tours.colon.title': 'Historic Colón Tour (Agua Clara y Fuerte San Lorenzo)',
    'tours.colon.desc': 'Discover the rich history of Colón, the impressive engineering of the Panama Canal, and spectacular natural landscapes in a carefully designed experience that combines heritage, culture, and nature, departing from Panama City.',
    'tours.colon.meta': 'Full day • Colón Province',
    'tours.colon.hl1': 'Fort San Lorenzo (UNESCO)',
    'tours.colon.hl2': 'Agua Clara Visitor Center',
    'tours.colon.hl3': 'Climatized Executive Units',
    'tours.colon.price_label': 'Min. 2 passengers',
    'tours.colon.price': '$125',

    // City Tour
    'tours.city.title': 'City Tour Panamá',
    'tours.city.desc': 'Discover the perfect blend of history, culture, and modernity that will take you through the most emblematic places in Panama City.',
    'tours.city.meta': '4-5 hours duration • Panama City',
    'tours.city.hl1': 'Miraflores Locks Entry',
    'tours.city.hl2': 'Casco Antiguo Walk',
    'tours.city.hl3': 'Bilingual Guide Available Upon Request',
    'tours.city.price_label': 'Up to 3 passengers',
    'tours.city.price': '$140',
    

    // Portobelo
    'tours.portobelo.title': 'Portobelo & Its Charms',
    'tours.portobelo.desc': 'A comprehensive tour of the Caribbean Coast combining Spanish colonial history, local culture, and paradise mangrove beaches.',
    'tours.portobelo.meta': 'Full day • Caribbean Coast',
    'tours.portobelo.hl1': 'Venas Azules Boat Ride',
    'tours.portobelo.hl2': 'Playa Blanca Beach Time',
    'tours.portobelo.hl3': 'San Felipe Church History',
    'tours.portobelo.price_label': 'Min. 2 passengers',
    'tours.portobelo.price': '$125',

    // Emberá
    'tours.embera.title': 'Emberá Cultural Tour',
    'tours.embera.desc': 'Live a unique experience of culture, tradition, and nature with the Emberá indigenous community. Cruise the historic Chagres River in a traditional canoe, share an authentic local lunch, enjoy cultural performances, and discover ancestral crafts in the heart of the national park.',
    'tours.embera.meta': 'Full day tour • Complete Itinerary • Chagres National Park',
    'tours.embera.hl1': 'Chagres Canoe Ride',
    'tours.embera.hl2': 'Traditional Emberá Lunch',
    'tours.embera.hl3': 'Ancestral Dances',
    'tours.embera.hl4': 'Crafts Exhibition',
    'tours.embera.hl5': 'Trip Coordinator',
    'tours.embera.not_inc': 'Not Included: Souvenirs, additional beverages, and tips.',
    'tours.embera.price_label': 'Per person',
    'tours.embera.price': '$110',
    
    // Services Section
    'services.header': 'OUR SERVICES',
    'services.title': 'Premium Mobility Solutions in Panama',
    'services.airport.tag': 'Most Popular',
    'services.airport.title': 'Airport Transfers',
    'services.airport.desc': 'Punctual door-to-door service to and from Tocumen International Airport (PTY). Flight tracking and professional reception.',
    'services.airport.link': 'Book Transfer →',
    'services.corporate.title': 'Executive Service',
    'services.corporate.desc': 'Executive transportation with professional driver for business meetings, corporate events, business visits and VIP services.',
    'services.corporate.link': 'Learn More →',
    'services.tours.title': 'Custom Panama Tours',
    'services.tours.desc': 'Discover the Panama Canal, Casco Antiguo, Amador and other iconic destinations with tailor-made itineraries.',
    'services.tours.link': 'Explore Tours →',
    'services.modal.tag': 'Service Details',
    'services.modal.howworks': 'How It Works:',
    'services.modal.quote': 'Quote via WhatsApp',
    
    'services.airport.subtitle': 'Tocumen International (PTY) & Marcos A. Gelabert (Albrook)',
    'services.airport.desc.long': 'Our premium airport service is engineered to eliminate travel stress. We coordinate every detail from flight tracking to luggage handling so your arrival or departure in Panama is completely seamless.',
    'services.airport.step1': 'Real-Time Flight Tracking: We monitor your flight path. If your arrival is delayed or early, your chauffeur will adjust accordingly.',
    'services.airport.step2': 'Professional Meet & Greets: Your driver will greet you in the arrivals area with a personalized sign bearing your name or corporate logo.',
    'services.airport.step3': 'Includes 60 minutes of complimentary waiting time after your flight lands, giving you ample time for customs and baggage claim.',
    'services.airport.step4': 'Luggage Assistance & Comfort: Full assistance with loading your luggage into an air-conditioned vehicle, complimentary bottled water, and all the amenities for a comfortable transfer.',
    'services.airport.note1': 'Includes toll fees (Corredor Sur).',
    'services.airport.note2': 'Child seats available upon prior request.',
    
    'services.corporate.subtitle': 'First-Class Corporate Mobility Solutions',
    'services.corporate.desc.long': 'Designed for corporate executives, business delegations, and business travelers who value absolute punctuality, confidentiality, and flawless execution.',
    'services.corporate.step1': 'By-the-Hour or Full-Day Service: Retain a dedicated vehicle and professional driver for your entire business itinerary.',
    'services.corporate.step2': 'Bilingual Professional Chauffeurs: Drivers trained in corporate protocol, navigation, and security, speaking fluent English and Spanish.',
    'services.corporate.step3': 'On-Board Executive Perks: Vehicles equipped with device chargers and amenities designed to keep you productive during your journey.',
    'services.corporate.step4': 'Flawless Logistics Coordination: Ideal for roadshows, corporate summits, and multi-destination meeting schedules.',
    'services.corporate.note2': 'Confidentiality and discretion guaranteed.',
    
    'services.tours.subtitle': 'Exclusive Experiences Tailored to You',
    'services.tours.desc.long': 'Explore the rich history, modern marvels, and breathtaking nature of Panama through a completely tailored private itinerary built around your pace and preferences.',
    'services.tours.step1': 'Tailored Itinerary Planning: Choose from iconic spots like the Panama Canal (Miraflores Locks), Casco Antiguo, Amador Causeway, or Gamboa Rainforest.',
    'services.tours.step2': 'Flexible Timing: No rigid schedules. Spend as much or as little time at each landmark as you wish.',
    'services.tours.step3': 'Personalized Local Assistance: Our drivers can guide you on the main attractions and recommendations during your trip.',
    'services.tours.step4': 'Premium Group Accommodations: Perfect for families, corporate groups, or VIP travelers wanting a relaxed, private excursion.',
    'services.tours.note1': 'Entrance tickets to museums or the Canal are coordinated separately.',
    'services.tours.note2': 'Custom lunch stop recommendations included.',
    'services.tours.note3': 'Professional tour guide available upon request (additional service).',

    'about.eyebrow': 'About us',
    'about.hero.title': 'Panama through local eyes',
    'about.hero.desc': 'We are a Panamanian company specializing in private transportation, tourism experiences, and corporate logistics. Since 2012, we have offered reliable mobility solutions for travelers, businesses, and events throughout Panama.',
    'about.stats.exp': 'Years of experience',
    'about.stats.guests': 'Guests served',
    'about.stats.destinations': 'Curated destinations',
    'about.stats.experiences': 'Private experiences',
    'about.story.header': 'Our story',
    'about.story.year1': 'Founded 2012',
    'about.story.title1': 'From a passion for Panama to a curated travel brand',
    'about.story.desc1': 'JM Transport Group was established in Panama with the goal of providing reliable, professional, and personalized transportation services. What began as a traveler-focused operation has evolved into a company specializing in tourism, corporate, and event logistics.',
    'about.story.year2': 'Today',
    'about.story.title2': 'Premium Transportation in Panama',
    'about.story.desc2': 'With over a decade of experience, we provide private transportation solutions for travelers, businesses, hotels, and events. Our commitment to punctuality, safety, and personalized service has allowed us to be part of thousands of experiences throughout the country.',
    'about.team.header': 'Meet the team',
    'about.team.member1.role': 'Founder & Lead Guide',
    'about.team.member1.bio': 'Born in Panama City, Carlos has spent over 15 years exploring every corner of the isthmus. His local knowledge and logistics expertise are the backbone of every tour.',
    'about.team.member2.role': 'Operations & Concierge',
    'about.team.member2.bio': 'With a background in luxury hospitality, Valeria ensures every detail is confirmed before you arrive — from airport pickup to that last sunset on Isla Perro.',
    'about.team.member3.role': 'Corporate Travel Specialist',
    'about.team.member3.bio': 'Diego manages our corporate accounts and group logistics, coordinating multi-day retreats with the precision that executive teams demand.',
    'about.cta.title': 'Ready to plan your experience?',
    'about.cta.desc': 'Talk to our concierge and let\'s design something remarkable.',
    'about.cta.btn': 'Contact us on WhatsApp →',
    'about.address.label': 'Address',
    'about.phone.label': 'Landline',
    'about.whatsapp': 'WhatsApp',

    'fleet.header.subtitle': 'OUR FLEET',
    'fleet.header.title': 'Travel with Style, Comfort & Security',
    'fleet.header.desc': 'Discover our diverse lineup of modern, impeccably maintained vehicles tailored to match your exact corporate, group, or VIP transportation requirements in Panama.',
    'fleet.filter.all': 'All Fleet',
    'fleet.filter.suv': 'SUVs',
    'fleet.filter.coaster': 'Group Vans & Coasters',
    'fleet.filter.vip': 'VIP Experience',
    'fleet.vip.tag': 'VIP Class',
    'fleet.passenger.label': 'Up to {passengers} passengers',
    'fleet.book.btn': 'Book Now',
    'fleet.perks.title': 'All Our Services Include:',
    'fleet.benefit.ac': 'Full air conditioning',
    'fleet.benefit.tracking': 'Real-Time flight tracking',
    'fleet.benefit.luggage': 'Luggage assistance',
    'fleet.benefit.water': 'Complimentary bottled water & snacks',
    'fleet.benefit.seats': 'Child seats available upon request',
    'fleet.benefit.drivers': 'Bilingual professional drivers',

    // Booking translations (English)
    'bk.heroTitle': "Book Your Premium Journey",
    'bk.heroDesc': "Experience Panama with the highest standards of reliability and luxury. Fill out the form below to secure your private transport or curated tour.",
    'bk.formTitle': "Reservation Details",
    'bk.alertFields': "Please fill in all required fields marked with an asterisk (*).",
    'bk.serviceTypeLabel': "What service do you need? *",
    'bk.selectServiceType': "Select a service type...",
    'bk.serviceTransfer': "Shuttle Service (One-way / Roundtrip)",
    'bk.serviceTour': "Curated Tour / Sightseeing",
    'bk.serviceCorporate': "Custom & Corporate Services",
    'bk.nameLabel': "Full Name *",
    'bk.emailLabel': "Email Address",
    'bk.phoneLabel': "Phone / WhatsApp Number *",
    'bk.peopleLabel': "Number of Passengers *",
    'bk.dateLabel': "Preferred Date *",
    'bk.notesLabel': "Special Requests or Dietary Requirements",
    'bk.notesPlaceholder': "Any specific requests for our team...",
    'bk.transferRouteLabel': "Transfer Route *",
    'bk.selectRoute': "Select route...",
    'bk.routeToHotel': "Airport ➔ Hotel / Destination",
    'bk.routeToAirport': "Hotel / Origin ➔ Airport",
    'bk.routeRoundtrip': "Roundtrip (Airport ➔ Hotel ➔ Airport)",
    'bk.airportLabel': "Panama Airport *",
    'bk.selectAirport': "Select airport...",
    'bk.flightNumLabel': "Flight Number *",
    'bk.flightTimeLabel': "Flight Arrival/Departure Time *",
    'bk.fleetLabel': "Select Preferred Vehicle Fleet *",
    'bk.selectVehicle': "Select a vehicle from our fleet...",
    'bk.tourSelectLabel': "Choose a Curated Tour *",
    'bk.selectTour': "Select a tour...",
    'bk.tourCustom': "Custom Personalized Tour",
    'bk.pickupLabel': "Pickup Location / Hotel *",
    'bk.tourDurationLabel': "Estimated Duration (Hours/Days) *",
    'bk.tourPlacesLabel': "Places of Interest *",
    'bk.tourPlacesPlaceholder': "e.g., Casco Viejo, Panama Canal, Amador Causeway...",
    'bk.budgetLabel': "Approximate Budget (USD)",
    'bk.budgetPlaceholder': "e.g., $500, $1500 (Optional)",
    'bk.experienceTypeLabel': "Desired Experience Type *",
    'bk.selectExperience': "Select style...",
    'bk.expVacation': "Leisure & Family Vacation",
    'bk.expAdventure': "Eco-Adventure & Nature",
    'bk.expLuxury': "VIP & Luxury Experience",
    'bk.corpNameLabel': "Company / Organization Name *",
    'bk.corpTypeLabel': "Type of Event *",
    'bk.corpTypePlaceholder': "e.g., Executive Retreat, Conference, Team Building",
    'bk.corpStaffLabel': "Staff or On-Site Coordination Requirements",
    'bk.corpStaffPlaceholder': "e.g., Bilingual coordinators, meet & greet staff at airport...",
    'bk.detailsLabel': "Detailed Description of Your Requirements *",
    'bk.detailsPlaceholder': "Please describe your ideal itinerary, schedules, or logistics plan in detail...",
    'bk.submitBtn': "Submit Booking Request",
    'bk.waNote': "⚡ After submission, you will be redirected to WhatsApp for instant coordination.",
    'bk.sidebarTitle': "Direct Contact",
    'bk.sidebarWhy': "Why choose JM Transport Group?",
    'bk.fleetTitle': "Our Premium Fleet",
    'bk.fleetDesc': "From executive SUVs to luxury sprinter vans and high-capacity buses."
  },
  es: {
    // Navbar
    'nav.home': 'Inicio',
    'nav.services': 'Servicios',
    'nav.tours': 'Tours',
    'nav.fleet': 'Flota',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.booking': 'Reservas',

    // Hero
    'hero.title': 'Explora Panamá con Comodidad, Seguridad y Confianza',
    'hero.subtitle': 'Transporte privado, traslados al aeropuerto y tours inolvidables por Panamá. Vive lo mejor del trópico con un toque ejecutivo de primera clase.',
    'hero.btn.contact': 'Contáctanos',
    'hero.btn.tours': 'Ver Tours',
    'hero.dock.drivers': 'Conductores Profesionales',
    'hero.dock.vehicles': 'Vehículos Cómodos',
    'hero.dock.transfers': 'Traslados Seguros',
    'hero.dock.prices': 'Precios Accesibles',

    // Footer
    'footer.description': 'Proveedor líder de transporte y logística turística en la República de Panamá desde 2012.',
    'footer.quicklinks': 'Enlaces Rápidos',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.faq': 'Preguntas Frecuentes',
    'footer.corporate': 'Viajes Corporativos',
    'footer.services': 'Servicios',
    'footer.airport': 'Traslados al Aeropuerto',
    'footer.citytours': 'Tours por la Ciudad',
    'footer.intercity': 'Destinos Nacionales',
    'footer.events': 'Eventos Especiales',
    'footer.location': 'Ubicación',
    'footer.address': 'Ave. Federico Boyd y Calle 51,\nEdificio Scotia Plaza, Piso 7,\nBella Vista, Ciudad de Panamá',
    'footer.phone': 'Teléfono fijo: 310-4785',
    'footer.rights': '© 2026 JM Transport Group Panamá. Todos los derechos reservados.',
    'about.contact.title': 'Contacto y Ubicación',
    'about.contact.address': 'Ave. Federico Boyd y Calle 51,\nEdificio Scotia Plaza, Piso 7,\nBella Vista, Ciudad de Panamá',
    'about.contact.phone': 'Teléfono fijo: 310-4785',
    
    // Tours
    'tours.header.subtitle': 'TOURS EXCLUSIVOS',
    'tours.header.title': 'Experiencias Premium en Panamá',
    'tours.header.desc': 'Itinerarios de lujo y corporativos diseñados para descubrir los destinos más icónicos de Panamá.',

    // San Blas
    'tours.sanblas.title': 'Pasadía San Blas',
    'tours.sanblas.desc': 'Sumérgete en el paraíso caribeño de las Islas San Blas, hogar del pueblo indígena Guna. Aguas cristalinas color turquesa, arenas blancas y una cultura ancestral viva hacen de este tour una experiencia única e inolvidable en el Caribe panameño.',
    'tours.sanblas.meta': 'Día completo • Archipiélago San Blas',
    'tours.sanblas.hl1': 'Transporte 4×4 Incluido',
    'tours.sanblas.hl2': 'Paseos en Bote entre Islas',
    'tours.sanblas.hl3': 'Recogida en tu Hotel',
    'tours.sanblas.hl4': 'Snorkel en Arrecifes',
    'tours.sanblas.hl5': 'Cultura Guna Yala',
    'tours.sanblas.not_inc': 'No Incluye: Almuerzo, bebidas y cuota de entrada al territorio Guna Yala.',
    'tours.sanblas.price_label': 'Desde',
    'tours.sanblas.price': '$125',

    // Monkey Tour
    'tours.monkey.title': 'Tour de Monos',
    'tours.monkey.desc': 'Descubre la biodiversidad del Canal de Panamá y conoce a sus residentes más famosos de cerca en su hábitat natural. Ideal para fotos y conectar con la naturaleza.',
    'tours.monkey.meta': 'Medio día • Zona del Canal de Panamá',
    'tours.monkey.hl1': 'Paseo en Lancha por el Canal',
    'tours.monkey.hl2': 'Avistamiento de Fauna',
    'tours.monkey.hl3': 'Retorno Seguro al Hotel',
    'tours.monkey.price_label': 'Por persona',
    'tours.monkey.price': '$85',

    // Beach Transfers
    'tours.playas.title': 'Traslados a Destinos Turísticos',
    'tours.playas.desc': 'Servicio de transporte privado cómodo y puntual hacia los principales destinos turísticos de Panamá.',
    'tours.playas.destinations': 'Destinos:  Buenaventura, Chiriquí, Boquete, Pedasí, Santa Catalina, las Mil Polleras, ferias, festivales y cualquier otro destino.',
    'tours.playas.meta': 'Ida / Vuelta • Disponible 24/7',
    'tours.playas.hl1': 'Vehículos Modernos Ejecutivos',
    'tours.playas.hl2': 'Equipaje sin Límites',
    'tours.playas.hl3': 'Atención Personalizada',
    'tours.playas.price_label': 'Hasta 4 pasajeros',
    'tours.playas.price': '$125',

    // Historic Colon
    'tours.colon.title': ' Tour Histórico de Colón (Agua Clara y Fuerte San Lorenzo)',
    'tours.colon.desc': 'Descubre la riqueza histórica de Colón, la impresionante ingeniería del Canal de Panamá y espectaculares paisajes naturales en una experiencia cuidadosamente diseñada que combina patrimonio, cultura y naturaleza, con salida desde la Ciudad de Panamá.',
    'tours.colon.meta': 'Día completo • Provincia de Colón',
    'tours.colon.hl1': 'Fuerte San Lorenzo (UNESCO)',
    'tours.colon.hl2': 'Centro de Visitantes Agua Clara',
    'tours.colon.hl3': 'Unidades Climatizadas A/C',
    'tours.colon.price_label': 'Mínimo 2 pers',
    'tours.colon.price': '$125',

    // City Tour
    'tours.city.title': 'Tour por la Ciudad de Panamá',
    'tours.city.desc': 'Descubre la mezcla perfecta de historia, cultura y modernidad que te llevará por los lugares más emblemáticos de la Ciudad de Panamá.',
    'tours.city.meta': '4 a 5 horas de trayecto • Ciudad de Panamá',
    'tours.city.hl1': 'Centro de Visitantes Miraflores',
    'tours.city.hl2': 'Caminata por Casco Antiguo',
    'tours.city.hl3': 'Guía Bilingüe Opcional Bajo Solicitud',
    'tours.city.price_label': 'Hasta 3 personas',
    'tours.city.price': '$140',

    // Portobelo
    'tours.portobelo.title': 'Portobelo y sus Encantos',
    'tours.portobelo.desc': 'Un tour integral por la Costa Caribe que combina historia colonial española, cultura afroantillana y playas paradisíacas de manglar.',
    'tours.portobelo.meta': 'Día completo • Costa Caribe',
    'tours.portobelo.hl1': 'Lancha por Venas Azules',
    'tours.portobelo.hl2': 'Relajación en Playa Blanca',
    'tours.portobelo.hl3': 'Fuertes e Iglesia Cristo Negro',
    'tours.portobelo.price_label': 'Mínimo 2 pers',
    'tours.portobelo.price': '$125',

    // Emberá
    'tours.embera.title': 'Tour Emberá Tradicional',
    'tours.embera.desc': 'Vive una experiencia única de cultura, tradición y naturaleza con la comunidad indígena Emberá. Navega por el río Chagres en canoa, comparte el almuerzo típico, disfruta de presentaciones culturales con danzas típicas y descubre las artesanías de uno de los pueblos originarios más fascinantes.',
    'tours.embera.meta': 'Día completo • Itinerario Completo • Parque Nacional Chagres',
    'tours.embera.hl1': 'Canoa por el Río Chagres',
    'tours.embera.hl2': 'Almuerzo Emberá Tradicional',
    'tours.embera.hl3': 'Danzas Típicas',
    'tours.embera.hl4': 'Exposición de Artesanías',
    'tours.embera.hl5': 'Coordinador de Viaje',
    'tours.embera.not_inc': 'No Incluye: Compras de artesanías, bebidas adicionales y propinas.',
    'tours.embera.price_label': 'Por persona',
    'tours.embera.price': '$110',

    // Services Section
    'services.header': 'NUESTROS SERVICIOS',
    'services.title': 'Soluciones Premium de Movilidad en Panamá',
    'services.airport.tag': 'Más Popular',
    'services.airport.title': 'Traslados al Aeropuerto',
    'services.airport.desc': 'Servicio puerta a puerta puntual desde y hacia Tocumen Internacional (PTY). Seguimiento de vuelos y recepción profesional.',
    'services.airport.link': 'Reservar Traslado →',
    'services.corporate.title': 'Servicio Ejecutivo',
    'services.corporate.desc': 'Transporte ejecutivo con conductor profesional para reuniones de negocios, eventos corporativos, visitas empresariales y servicios VIP.',
    'services.corporate.link': 'Más Información →',
    'services.tours.title': 'Tours personalizados de Panamá',
    'services.tours.desc': 'Descubre el Canal de Panamá, Casco Antiguo, Amador y otros destinos icónicos con itinerarios diseñados a tu medida.',
    'services.tours.link': 'Explorar Tours →',
    'services.modal.tag': 'Detalles del Servicio',
    'services.modal.howworks': 'Cómo Funciona:',
    'services.modal.quote': 'Solicitar Cotización por WhatsApp',
    
    // Airport Service Details
    'services.airport.subtitle': 'Tocumen Internacional (PTY) y Marcos A. Gelabert (Albrook)',
    'services.airport.desc.long': 'Nuestro servicio de aeropuerto premium está diseñado para eliminar el estrés de los viajes. Coordinamos cada detalle desde el rastreo de vuelos hasta el manejo del equipaje para que tu llegada o salida de Panamá sea completamente fluida.',
    'services.airport.step1': 'Rastreo de Vuelos en Tiempo Real: Monitoreamos la ruta de tu vuelo. Si tu llegada se retrasa o adelanta, tu chófer se ajustará en consecuencia.',
    'services.airport.step2': 'Recepción Profesional: Tu conductor te recibirá en el área de llegadas con un cartel personalizado con tu nombre o logo corporativo.',
    'services.airport.step3': 'Tiempo de Espera Gratuito: Incluye 60 minutos de tiempo de espera gratuito después de que tu vuelo aterrice, dándote tiempo suficiente para aduanas y reclamación de equipaje.',
    'services.airport.step4': 'Asistencia de Equipaje y Comodidad: Asistencia completa para cargar tus maletas en un vehículo con aire acondicionado, agua embotellada de cortesía y todas las comodidades para un traslado confortable.',
    'services.airport.note1': 'Incluye peajes (Corredor Sur).',
    'services.airport.note2': 'Asientos para niños disponibles bajo solicitud previa.',
    
    // Corporate Service Details
    'services.corporate.subtitle': 'Soluciones de Movilidad Corporativa de Primera Clase',
    'services.corporate.desc.long': 'Diseñado para ejecutivos corporativos, delegaciones empresariales y viajeros de negocios que valoran la puntualidad absoluta, confidencialidad y ejecución impecable.',
    'services.corporate.step1': 'Servicio por Hora o Día Completo: Retén un vehículo dedicado y conductor profesional para todo tu itinerario comercial.',
    'services.corporate.step2': 'Chóferes Profesionales Bilingües: Conductores capacitados en protocolo corporativo, navegación y seguridad, hablando fluidamente inglés y español.',
    'services.corporate.step3': 'Beneficios Ejecutivos a Bordo: Vehículos equipados con cargadores para dispositivos y comodidades diseñadas para mantenerte productivo durante el trayecto.',
    'services.corporate.step4': 'Coordinación Logística Impecable: Ideal para encuentros de negocios, cumbres corporativas y agendas de reuniones en múltiples destinos.',
    'services.corporate.note2': 'Confidencialidad y discreción garantizadas.',
    
    // Tours Service Details
    'services.tours.subtitle': 'Experiencias Exclusivas Diseñadas a Tu Medida',
    'services.tours.desc.long': 'Explora la rica historia, maravillas modernas y la naturaleza impresionante de Panamá a través de un itinerario completamente personalizado diseñado alrededor de tu ritmo y preferencias.',
    'services.tours.step1': 'Planificación de Itinerario Personalizado: Elige entre lugares icónicos como el Canal de Panamá (Esclusas de Miraflores), Casco Antiguo, Calzada de Amador o la Selva de Gamboa.',
    'services.tours.step2': 'Horarios Flexibles: Sin horarios rígidos. Pasa tanto o tan poco tiempo como desees en cada sitio de interés.',
    'services.tours.step3': 'Asistencia Local Personalizada: Nuestros conductores pueden orientarte sobre los principales atractivos y recomendaciones durante tu recorrido.',
    'services.tours.step4': 'Acomodaciones para Grupos Premium: Perfecto para familias, grupos corporativos o viajeros VIP que desean una excursión privada y relajada.',
    'services.tours.note1': 'Las entradas a museos o al Canal se coordinan por separado.',
    'services.tours.note2': 'Recomendaciones de paradas para almuerzo personalizado incluidas.',
    'services.tours.note3': 'Guía turístico profesional disponible bajo solicitud (servicio adicional).',
    

    // About Us
    'about.eyebrow': 'Acerca de nosotros',
    'about.hero.title': 'Panamá a través de ojos locales',
    'about.hero.desc': 'Somos una empresa panameña especializada en transporte privado, experiencias turísticas y logística corporativa. Desde 2012, ofrecemos soluciones de movilidad confiables para viajeros, empresas y eventos en todo Panamá.',
    'about.stats.exp': 'Años de experiencia',
    'about.stats.guests': 'Huéspedes atendidos',
    'about.stats.destinations': 'Destinos curados',
    'about.stats.experiences': 'Experiencias privadas',
    'about.story.header': 'Nuestra historia',
    'about.story.year1': 'Fundada 2012',
    'about.story.title1': 'De una pasión por Panamá a una marca de viajes curada',
    'about.story.desc1': 'JM Transport Group nació en Panamá con el objetivo de ofrecer un servicio de transporte confiable, profesional y personalizado. Lo que comenzó como una operación enfocada en la atención al viajero se ha convertido en una empresa especializada en movilidad turística, corporativa y logística de eventos.',
    'about.story.year2': 'Hoy',
    'about.story.title2': 'Movilidad Premium en Panamá',
    'about.story.desc2': 'Con más de una década de experiencia, brindamos soluciones de transporte privado para viajeros, empresas, hoteles y eventos. Nuestro compromiso con la puntualidad, la seguridad y la atención personalizada nos ha permitido acompañar miles de experiencias en todo el país.',
    'about.team.header': 'Conoce al equipo',
    'about.team.member1.role': 'Fundador y Guía Principal',
    'about.team.member1.bio': 'Nacido en la Ciudad de Panamá, Carlos ha pasado más de 15 años explorando cada rincón del istmo. Su conocimiento local y experiencia en logística son la base de cada tour.',
    'about.team.member2.role': 'Operaciones y Conserjería',
    'about.team.member2.bio': 'Con experiencia en hospitalidad de lujo, Valeria asegura que cada detalle esté confirmado antes de tu llegada — desde la recogida en el aeropuerto hasta ese último atardecer en Isla Perro.',
    'about.team.member3.role': 'Especialista en Viajes Corporativos',
    'about.team.member3.bio': 'Diego gestiona nuestras cuentas corporativas y logística de grupos, coordinando retiros de varios días con la precisión que los equipos ejecutivos demandan.',
    'about.cta.title': '¿Listo para planificar tu experiencia?',
    'about.cta.desc': 'Habla con nuestro conserje y diseñemos algo extraordinario.',
    'about.cta.btn': 'Contáctanos por WhatsApp →',
    'about.address.label': 'Dirección',
    'about.phone.label': 'Teléfono Fijo',
    'about.whatsapp': 'WhatsApp',
    
    // Fleet Section
    'fleet.header.subtitle': 'NUESTRA FLOTA',
    'fleet.header.title': 'Viaja con Estilo, Comodidad y Seguridad',
    'fleet.header.desc': 'Descubre nuestra diversa flota, Contamos con flota propia y una red de vehículos asociados seleccionados para ofrecer la solución de transporte ideal para cada servicio.',
    'fleet.filter.all': 'Toda la Flota',
    'fleet.filter.suv': 'SUVs',
    'fleet.filter.coaster': 'Furgonetas y Autobuses',
    'fleet.filter.vip': 'Experiencia VIP',
    'fleet.vip.tag': 'Clase VIP',
    'fleet.passenger.label': 'Hasta {passengers} pasajeros',
    'fleet.book.btn': 'Reservar Ahora',
    'fleet.perks.title': 'Todos Nuestros Servicios Incluyen:',
    'fleet.benefit.ac': 'Aire acondicionado completo',
    'fleet.benefit.tracking': 'Rastreo de vuelos en tiempo real',
    'fleet.benefit.luggage': 'Asistencia de equipaje',
    'fleet.benefit.water': 'Agua embotellada y snacks de cortesía',
    'fleet.benefit.seats': 'Asientos para niños disponibles bajo solicitud',
    'fleet.benefit.drivers': 'Conductores profesionales bilingües',

    // Booking translations (Spanish)
    'bk.heroTitle': "Reserva tu Viaje Premium",
    'bk.heroDesc': "Experimenta Panamá con los más altos estándares de confiabilidad y lujo. Llena el formulario a continuación para asegurar tu transporte privado o servicio personalizado.",
    'bk.formTitle': "Detalles de la Reservación",
    'bk.alertFields': "Por favor, completa todos los campos obligatorios marcados con un asterisco (*).",
    'bk.serviceTypeLabel': "¿Qué servicio necesita? *",
    'bk.selectServiceType': "Seleccione un tipo de servicio...",
    'bk.serviceTransfer': "Servicio de Traslado",
    'bk.serviceTour': "Tours Organizados / Paseos",
    'bk.serviceCorporate': "Servicios Personalizados y Corporativos",
    'bk.nameLabel': "Nombre Completo *",
    'bk.emailLabel': "Correo Electrónico",
    'bk.phoneLabel': "Número de Teléfono / WhatsApp *",
    'bk.peopleLabel': "Cantidad de Personas / Asistentes *",
    'bk.dateLabel': "Fecha Estimada *",
    'bk.notesLabel': "Solicitudes Especiales o Preferencias",
    'bk.notesPlaceholder': "Cualquier detalle adicional para nuestro equipo...",
    'bk.transferRouteLabel': "Ruta del Traslado *",
    'bk.selectRoute': "Seleccione la ruta...",
    'bk.routeToHotel': "Aeropuerto ➔ Hotel / Destino",
    'bk.routeToAirport': "Hotel / Origen ➔ Aeropuerto",
    'bk.routeRoundtrip': "Ida y Vuelta (Aeropuerto ➔ Hotel ➔ Aeropuerto)",
    'bk.airportLabel': "Aeropuerto en Panamá *",
    'bk.selectAirport': "Seleccione el aeropuerto...",
    'bk.flightNumLabel': "Número de Vuelo *",
    'bk.flightTimeLabel': "Hora del Vuelo *",
    'bk.fleetLabel': "Seleccione el Tipo de Vehículo de la Flota *",
    'bk.selectVehicle': "Seleccione un vehículo de nuestra flota...",
    'bk.tourSelectLabel': "Elija un Tour *",
    'bk.selectTour': "Seleccione un tour...",
    'bk.tourCustom': "Tour Personalizado a Medida",
    'bk.pickupLabel': "Lugar de Recogida / Hotel *",
    'bk.tourDurationLabel': "Duración Estimada (Horas/Días) *",
    'bk.tourPlacesLabel': "Lugares de Interés *",
    'bk.tourPlacesPlaceholder': "Ej: Casco Viejo, Canal de Panamá, Calzada de Amador...",
    'bk.budgetLabel': "Presupuesto Aproximado (USD)",
    'bk.budgetPlaceholder': "Ej: $500, $1500 (Opcional)",
    'bk.experienceTypeLabel': "Tipo de Experiencia Deseada *",
    'bk.selectExperience': "Seleccione un estilo...",
    'bk.expVacation': "Vacacional y Familiar",
    'bk.expAdventure': "Eco-Aventura y Naturaleza",
    'bk.expLuxury': "Experiencia VIP y de Lujo",
    'bk.corpNameLabel': "Nombre de la Empresa / Organización *",
    'bk.corpTypeLabel': "Tipo de Evento *",
    'bk.corpTypePlaceholder': "Ej: Retiro Ejecutivo, Congreso, Team Building",
    'bk.corpStaffLabel': "Requerimientos de Personal o Coordinación",
    'bk.corpStaffPlaceholder': "Ej: Coordinadores bilingües, personal de bienvenida en aeropuerto...",
    'bk.detailsLabel': "Descripción Detallada de lo que Busca *",
    'bk.detailsPlaceholder': "Describa detalladamente el itinerario ideal, horarios o plan logístico que requiere...",
    'bk.submitBtn': "Enviar Solicitud de Reserva",
    'bk.waNote': "⚡ Después del envío, serás redirigido a WhatsApp para una confirmación instantánea.",
    'bk.sidebarTitle': "Contacto Directo",
    'bk.sidebarWhy': "¿Por qué elegir JM Transport Group?",
    'bk.fleetTitle': "Nuestra Flota Premium",
    'bk.fleetDesc': "Desde SUVs ejecutivas hasta vans de lujo y autobuses de alta capacidad."
  }
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>('es');

  const toggleLang = () => setLang(prev => (prev === 'es' ? 'en' : 'es'));

  const t = (key: string): string => {
    return (translations[lang] as Record<string, string>)[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used inside LanguageProvider');
  return ctx;
}